# /bin/bash

#PBS -A NCMAS-ch81
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=4:mem=4gb
#PBS -N Trinity_job3_vanilla

set -e

mem='4G'

# Set trap
# EXIT runs on any exit, signalled or not.
finish(){
		echo "$(date): Saving Trinity.fasta, Trinity.fasta.gene_trans_map, Trinity.timing, partitioned_reads.files.list and recursive_trinity.cmds. Everything else will be deleted"
		mv ${LOCALOUT}/Trinity* ${outpath}/${sampleout}/.
                mv ${LOCALOUT}/partitioned_reads.files.list* ${outpath}/${sampleout}/.
		mv ${LOCALOUT}/recursive_trinity.cmds* ${outpath}/${sampleout}/.
		singularity exec ${simg} perl /usr/local/bin/trinityrnaseq/util/TrinityStats.pl ${outpath}/${sampleout}/Trinity.fasta > ${outpath}/${sampleout}/Trinity.fasta.stats
		echo "$(date): Finished Trinity!"
}
trap finish EXIT

# Set variables
sample=Test
sampleout=${sample}_trinity_v2.8.4
outpath=/30days/rosemariesadsad/tracy/SIH-Flashlite-Trinity/Test_vanilla
simg=/30days/rosemariesadsad/nat/trint.simg
first=/30days/rosemariesadsad/tracy/SIH-Flashlite-Trinity/sample_data/reads.left.fq.gz
second=/30days/rosemariesadsad/tracy/SIH-Flashlite-Trinity/sample_data/reads.right.fq.gz

# Unpack trinity_1.tar to TMPDIR
export LOCALOUT=${TMPDIR}/${sampleout}
mkdir -p ${LOCALOUT}
tar -xf ${outpath}/${sampleout}/trinity_2.tar -C ${LOCALOUT}
mv ${LOCALOUT}/trinity_2/* ${LOCALOUT}
rm -rf ${LOCALOUT}/trinity_2
cd ${LOCALOUT}

# Update paths
echo "$(date): Create new partitioned_reads.files.list containing new paths..."
find ${PWD}/ -iname '*trinity.reads.fa' > partitioned_reads.files.list
echo "$(date): Updating paths for recursive_trinity.cmds"
perl -pi.bak -e 's|--single \"[\S]+'${sampleout}'|--single "'${PWD}'|g' recursive_trinity.cmds
perl -pi.bak2 -e 's|--output \"[\S]+'${sampleout}'|--output "'${PWD}'|g' recursive_trinity.cmds

# Run trinity, stop after inchworm, do not run chrysalis
singularity exec -B ${LOCALOUT} ${simg} Trinity \
		--seqType fq \
                --max_memory ${mem} \
                --left ${first} \
                --right ${second} \
                --no_normalize_reads \
		--CPU ${NCPUS} \
                --output ${LOCALOUT} \
                --verbose

echo "$(date): Finished job 3 of Trinity"

